package jgbe;

/*
 *  IMPORTANT: THIS FILE IS AUTOGENERATED
 *
 *  Any modifications to this file will be lost when regenerating it.
 *  Modify the corresponding .jpp file instead, and regenerate this file.
 */

import java.io.InputStream;
import java.io.OutputStream;
import java.util.Enumeration;
import java.util.Vector;

public class VFSRoot implements IVFSNode {
	private String name;
	private Vector<IVFSNode> children = new Vector<IVFSNode>();

	public VFSRoot(String name) {
		this.name = name;
	}

	public boolean exists() {
		return true;
	};

	public boolean isFile() {
		return false;
	}

	public boolean isDir() {
		return true;
	}

	public String getURL() {
		return "vfsroot://";
	}

	public String getName() {
		return name;
	}

	public InputStream getInputStream() {
		return null;
	}

	public OutputStream getOutputStream() {
		return null;
	}

	public Enumeration<IVFSNode> getChildren() {
		return children.elements();
	}

	public IVFSNode createFile(String name) {
		return null;
	}

	public IVFSNode createDir(String name) {
		return null;
	}

	public void delete(String name) {
	}

	public void addNode(IVFSNode newnode) {
		if (newnode == null)
			return;

		children.addElement(newnode);
	}

	static IVFSNode getRoot() {
		VFSRoot root = new VFSRoot("root/");
		root.addNode(new VFSJar("jar/", "/"));

		return root;
	}
};
