package jgbe;
/*
 *  IMPORTANT: THIS FILE IS AUTOGENERATED
 *
 *  Any modifications to this file will be lost when regenerating it.
 *  Modify the corresponding .jpp file instead, and regenerate this file.
 */




public interface IAudioListener {

 public void writeAudioSample(byte[] s);
 public void writeAudioSample(byte l, byte r);

 public void reset();
 public void setDumpStream(java.io.DataOutputStream dos);
}
